name: "CI"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

jobs:

  test-action:
    name: "Github Action Test"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
        channel:
          - "stable"
          - "nightly"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Test Local Action"
        uses: "flox/install-flox-action@main"
        with:
          channel: "${{ matrix.channel }}"

      - name: "Test Local Action"
        uses: "./"
        with:
          environment: "flox/nb"
          command: "python --version"
